name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: samin/mysql-action@v1.3
      with:
        mysql root password: root
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: testdb
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: root
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: root
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
 
