name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.19
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 13.1 # optional, default is 10.x
    - name: Setup MySQL & Build with Maven
      run: mysql -h 127.0.0.1 --port 3306 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET latin1;' && sudo npm install -g node-gyp && mvn -B package --file pom.xml
 
